fix, ui: ROOT_FQDN in upgrade script

diff --git a/machines/eb-app-ui/home/ui/upgrade-galaxy-dev b/machines/eb-app-ui/home/ui/upgrade-galaxy-dev
--- a/machines/eb-app-ui/home/ui/upgrade-galaxy-dev
+++ b/machines/eb-app-ui/home/ui/upgrade-galaxy-dev
@@ -6,6 +6,18 @@ LOCAL="/tmp/galaxy"
 UI="$LOCAL/machines/eb-app-ui/home/ui"
 APP="$UI/galaxy-dev"
 
+# get ROOT FQDN
+[[ -z "$ROOT_FQDN" ]] && \
+    ROOT_FQDN=$(ack "^export const ROOT =" \
+                  /home/ui/galaxy-dev/src/lib/config.ts | \
+                  cut -d'"' -f2 | cut -d '/' -f3)
+if [[ -z "$ROOT_FQDN" ]]; then
+    echo "error: ROOT_FQDN is not found"
+    exit 1
+else
+   echo "ROOT_FQDN: $ROOT_FQDN"
+fi
+
 # get KRATOS FQDN
 [[ -z "$KRATOS_FQDN" ]] && \
     KRATOS_FQDN=$(ack "^export const KRATOS =" \
@@ -22,6 +34,7 @@ fi
 rm -rf $LOCAL
 git clone --depth=1 $REMOTE $LOCAL
 
+sed -i "s/___ROOT_FQDN___/$ROOT_FQDN/" $APP/src/lib/config.ts
 sed -i "s/___KRATOS_FQDN___/$KRATOS_FQDN/" $APP/src/lib/config.ts
 cat $APP/src/lib/config.ts
 
